name: Maven Build
on:
  push:
    branches:
      - master

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build with Maven'
        run: mvn clean install
