name: JMH Benchmark
on:
  push:
    branches:
      - master

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build with Maven'
        run: mvn clean install
      - name: 'Upload Java Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'java-artifact'
          path: 'jmh/target/jmh-.jar'
  linux-jmh-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: MAVEN_OPTS="-Xms512m -Xmx512m -XX:+AlwaysPreTouch" mvn --batch-mode jmh:benchmark
