name: JMH Benchmark
on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  jmh-benchmark:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: MAVEN_OPTS="-Xms512m -Xmx512m -XX:+AlwaysPreTouch" mvn --batch-mode jmh:benchmark
